### PR TITLE
Finding api improvements

### PR DESCRIPTION
**Pull request by piggydoughnut**
## Goal of the pull request:
* [ ] Documentation
* [ ] Bugfix
* [ ] Feature (New!)
* [x] Enhancement

## Description
**fidItemsByKeywords** accepts parameters now - keywords, pageNumber, limit, sortOrder. It still supports passing just one keyword.

Will highly appreciate if you update the npm package if all is good.

### CODE REVIEW

**Comment by piggydoughnut** [comment]
Hey :) Thank you for your merge! Please re-publish the npm package when you have a moment. 🤗

**Comment by pajaydev** [comment]
@piggydoughnut  Sorry for the delay. Published it in `ebay-node-api@2.7.1`

**Comment by zslabs** [comment]
Seeing regressions with this release - a single keyword `...findItemsByKeywords(term)...` throws `Keyword is missing, Keyword is required` 

`2.7.0` works as expected, but `2.7.1` has the issue.

**Comment by pajaydev** [comment]
@zslabs From this version, we have changed `Keyword` to `Keywords`.  Do you want me to use keyword ?.

**Comment by zslabs** [comment]
@pajaydev Thanks for the response - I may not have worded by question correctly, but using the example from README:

```
//This call searches for items on eBay by a keyword query (keywords).
ebay.findItemsByKeywords('iphone').then((data) => {
    console.log(data);
}, (error) => {
    console.log(error);
});
```

Throws an error now for me. This is the exact code that worked previously in `2.7.0` - does the README need to be updated?

**Comment by pajaydev** [comment]
@zslabs  Gotcha. Fixed it in `ebay-node-api@2.7.2`. Sorry for the inconvinence

**Comment by zslabs** [comment]
@pajaydev Thanks for the quick-fix! All's well again. Have a great day.

**Pull request merged**
