### PR TITLE
Get picture URL large on FindingService calls

### PR DESCRIPTION
**Pull request by sghael**
## Goal of the pull request:
* [ ] PictureURLLarge Feature (New!)

## Description
Add output selector(1) to be `PictureURLLarge` which returns a larger (up to 400x400) image
See: https://developer.ebay.com/DevZone/finding/CallRef/types/OutputSelectorType.html

Test updated.  No other functionality changed.

Ultimately, this API needs a way to add output selectors selectively.

### CODE REVIEW

**Comment by sghael** [comment]
Any thoughts on this PR?

**Comment by pajaydev** [comment]
@sghael  We have to check to do this dynamically, as of now I will merge. I will try to refactor it.

**Comment by sghael** [comment]
hi @pajaydev - any update on merging this?

**Comment by pajaydev** [comment]
@sghael  I merged it already.

**Comment by sghael** [comment]
thank you!

**Pull request merged**
